name: datum_models
version: "0.1.0"
config-version: 2
profile: datum

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  datum_models:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
    morpho:
      +schema: morpho
      staging:
        +materialized: view
      marts:
        +materialized: table
    rwa:
      +schema: rwa
      staging:
        +materialized: view
      marts:
        +materialized: table
    sui:
      +schema: sui
      staging:
        +materialized: view
      intermediate:
        +materialized: view
      marts:
        +materialized: table
