select
  event_id,
  run_id,
  source_id,
  fetched_at,
  lower(protocol)                       as protocol,
  tx_digest,
  ts,
  (ts at time zone 'UTC')::date         as day,
  liquidator,
  borrower,
  collateral_asset,
  collateral_amount,
  collateral_price,
  collateral_usd,
  debt_asset,
  debt_amount,
  debt_price,
  debt_usd,
  treasury_amount,
  gas_used_mist::double precision       as gas_used_mist,
  gas_usd,
  checkpoint
from {{ source('sui_raw', 'raw_liquidation_events') }}
